# What?
#
# Tag and release an arbitrary ref. Uploads to an internal archive for further processing.
#
# How?
#
# After checking out and testing the provided ref, the image is built and uploaded.
#
# When?
#
# Manual trigger or cron job every wednesday morning.
# action will check if a new commit was added if not should do nothing

name: "Release to Cloud"
run-name: "Release to Cloud off of ${{ inputs.ref }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (sha or branch name) to use"
        type: string
        default: "main"
        required: true
      package_test_command:
        description: "Package test command"
        type: string
        default: "python -c \"import dbt.adapters.bigquery\""
        required: true
      skip_tests:
        description: "Should the tests be skipped? (default to false)"
        type: boolean
        required: true
        default: false

  schedule:
    - cron: '0 13 * * 3' # Every Wednesday at 8:00 AM central time

defaults:
  run:
    shell: bash

jobs:
  get-last-successful-release-run:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.get_last_successful_release_run.outputs.commit_sha }}
    steps:
      - name: Get last successful Release to Cloud run details
        id: get_last_successful_release_run
        run: |
          last_run_url=$(curl --silent -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=workflow_dispatch&status=success&branch=main&workflow_file=release-internal.yml" | jq -r '.workflow_runs[0].url')
          if [ -z "$last_run_url" ]; then
            echo "No successful Release to Cloud run found."
            exit 1
          fi
          echo "Last run URL: $last_run_url"
          commit_sha=$(curl --silent -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$last_run_url" | jq -r '.head_sha')
          if [ -z "$commit_sha" ]; then
            echo "No commit SHA found for the last successful run."
            exit 1
          fi
          echo "Commit SHA: $commit_sha"
          echo "commit_sha=$commit_sha" >> "$GITHUB_OUTPUT"

  check-for-new-commits:
    runs-on: ubuntu-latest
    needs: get-last-successful-release-run
    outputs:
      latest_commit_sha: ${{ steps.check_new_commits.outputs.latest_commit_sha }}
      has_new_commits: ${{ steps.check_new_commits.outputs.has_new_commits }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for new commits since last Release to Cloud run
        id: check_new_commits
        run: |
          last_released_commit_sha=${{ needs.get-last-successful-release-run.outputs.commit_sha }}
          echo "Last released commit SHA: $last_released_commit_sha"
          latest_commit_sha=$(git rev-parse ${{ inputs.ref }})
          echo "Latest commit SHA: $latest_commit_sha"
          if [ "$last_released_commit_sha" != "$latest_commit_sha" ]; then
            echo "has_new_commits=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_new_commits=false" >> "$GITHUB_OUTPUT"
          fi
          echo "latest_commit_sha=$latest_commit_sha" >> "$GITHUB_OUTPUT"

  invoke-reusable-workflow:
    needs: check-for-new-commits
    if: needs.check-for-new-commits.outputs.has_new_commits == 'true'
    name: "Build and Release Internally"
    uses: "dbt-labs/dbt-release/.github/workflows/internal-archive-release.yml@main"
    with:
      package_test_command: "${{ inputs.package_test_command }}"
      dbms_name: "bigquery"
      ref: "${{ inputs.ref }}"
      skip_tests: "${{ inputs.skip_tests }}"
    secrets: "inherit"
