# What?
#
# Tag and release an arbitrary ref. Uploads to an internal archive for further processing.
#
# How?
#
# After checking out and testing the provided ref, the image is built and uploaded.
#
# When?
#
# Manual trigger or cron job every wednesday morning.

name: "Release to Cloud"
run-name: "Release to Cloud off of ${{ inputs.ref }}"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (sha or branch name) to use"
        type: string
        default: "main"
        required: true
      package_test_command:
        description: "Package test command"
        type: string
        default: "python -c \"import dbt.adapters.bigquery\""
        required: true
      skip_tests:
        description: "Should the tests be skipped? (default to false)"
        type: boolean
        required: true
        default: false

  schedule:
    - cron: '0 13 * * 3' # Every Wednesday at 8:00 AM central time

defaults:
  run:
    shell: bash

jobs:
  get-latest-release:
    runs-on: ubuntu-latest
    outputs:
      latest_release: ${{ steps.get_latest_release.outputs.latest_release }}
    steps:
      - name: Get latest release
        id: get_latest_release
        run: |
          latest_release=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "::set-output name=latest_release::$latest_release"

  check-for-new-commits:
    runs-on: ubuntu-latest
    needs: get-latest-release
    outputs:
      new_commits: ${{ steps.check_new_commits.outputs.new_commits }}
    steps:
      - name: Check for new commits since last release
        id: check_new_commits
        run: |
          last_release_date=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ needs.get-latest-release.outputs.latest_release }}" | jq -r .published_at)
          new_commits=$(git rev-list --count --since="$last_release_date" ${{ inputs.ref }})
          echo "::set-output name=new_commits::$new_commits"

  invoke-reusable-workflow:
    if: needs.check-for-new-commits.output.new_commits != '0'
    name: "Build and Release Internally"
    uses: "dbt-labs/dbt-release/.github/workflows/internal-archive-release.yml@main"
    with:
      package_test_command: "${{ inputs.package_test_command }}"
      dbms_name: "bigquery"
      ref: "${{ inputs.ref }}"
      skip_tests: "${{ inputs.skip_tests }}"
    secrets: "inherit"
